# Generated by Django 5.1.7 on 2025-04-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catshelf_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.JSONField(max_length=256),
        ),
    ]
